# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asmgr < Formula
  desc "Terminal UI for managing multiple AI coding assistant CLI sessions"
  homepage "https://github.com/izll/agent-session-manager"
  version "0.9.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/izll/agent-session-manager/releases/download/v0.9.1/asmgr_0.9.1_darwin_amd64.tar.gz"
      sha256 "59c7e2cf4088038d4fb7ea4740df0cbbc4c770234c9d9d640bb207985dd8f30b"

      define_method(:install) do
        bin.install "asmgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/izll/agent-session-manager/releases/download/v0.9.1/asmgr_0.9.1_darwin_arm64.tar.gz"
      sha256 "37f6188b85cf6c9e3460e49fc3fac353128c2e4d5277f8e68c5e7c790978ad44"

      define_method(:install) do
        bin.install "asmgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/izll/agent-session-manager/releases/download/v0.9.1/asmgr_0.9.1_linux_amd64.tar.gz"
      sha256 "667e4d6906d5974171c08d4419277d53a80532b03462e180aeb460c6d96b365f"
      define_method(:install) do
        bin.install "asmgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/izll/agent-session-manager/releases/download/v0.9.1/asmgr_0.9.1_linux_arm64.tar.gz"
      sha256 "921b88c5e4cf696420c17b2f4166656de8ed2b9e2004f2aab484023d542192fd"
      define_method(:install) do
        bin.install "asmgr"
      end
    end
  end
end
